"""
Poster Layout — Projek Badar Task 91 (G2)
Poster layout template untuk output gambar SIDIX.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any

logger = logging.getLogger(__name__)


@dataclass
class PosterTemplate:
    """Definisi template layout poster."""

    name: str
    width: int
    height: int
    title_region: dict     # {"x": 0, "y": 0, "w": width, "h": 200}
    image_region: dict     # {"x": 0, "y": 200, "w": width, "h": height-300}
    footer_text: str = "Generated by SIDIX"


TEMPLATES: dict[str, PosterTemplate] = {
    "a4_portrait": PosterTemplate(
        name="a4_portrait",
        width=2480,
        height=3508,
        title_region={"x": 0, "y": 0, "w": 2480, "h": 400},
        image_region={"x": 0, "y": 400, "w": 2480, "h": 2908},
        footer_text="Generated by SIDIX",
    ),
    "social_square": PosterTemplate(
        name="social_square",
        width=1080,
        height=1080,
        title_region={"x": 0, "y": 0, "w": 1080, "h": 120},
        image_region={"x": 0, "y": 120, "w": 1080, "h": 880},
        footer_text="Generated by SIDIX",
    ),
    "social_landscape": PosterTemplate(
        name="social_landscape",
        width=1920,
        height=1080,
        title_region={"x": 0, "y": 0, "w": 1920, "h": 100},
        image_region={"x": 0, "y": 100, "w": 1920, "h": 900},
        footer_text="Generated by SIDIX",
    ),
}


def apply_poster_template(
    image_path: str,
    template_name: str,
    title: str,
    output_path: str,
) -> dict:
    """
    Terapkan template poster ke gambar.

    STUB — TODO: implementasikan dengan PIL:
    1. Buat canvas baru sesuai dimensi template.
    2. Tempel gambar ke image_region.
    3. Render title text di title_region (PIL ImageDraw).
    4. Tambahkan footer_text di bagian bawah.
    5. Simpan ke output_path.

    Returns:
        dict berisi status, template, dan output_path.
    """
    template = TEMPLATES.get(template_name)
    if template is None:
        available = list(TEMPLATES.keys())
        logger.warning(
            "Template '%s' tidak ditemukan. Tersedia: %s", template_name, available
        )
        return {
            "status": "error",
            "error": f"Template '{template_name}' tidak ditemukan. Tersedia: {available}",
        }

    logger.info(
        "apply_poster_template() stub: template='%s', title='%s', output='%s'",
        template_name,
        title,
        output_path,
    )

    # TODO: wire PIL canvas composition
    return {
        "status": "stub",
        "template": template_name,
        "output": output_path,
        "dimensions": f"{template.width}x{template.height}",
    }
